packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@prisma/engines"
  - "prisma"
  - "esbuild"
  - "sharp"
  - "msgpackr-extract"
  - "unrs-resolver"
